version: '3'
services:
  frontend:
    build: .
    ports:
      - "80:80"
  api:
    build: ../api
    ports:
      - "4000:4000"
    depends_on: 
      - db
    links:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw #replace with your root password
      MYSQL_DATABASE: testdb #replace with your database name
      MYSQL_USER: user #replace with your username
      MYSQL_PASSWORD: password #replace with your password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
