version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password #replace with your root password
      MYSQL_DATABASE: arts_shop #replace with your database name
      MYSQL_USER: user #replace with your username
      MYSQL_PASSWORD: password #replace with your password
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
